name: dake
version: 1.0.3
description: Dake task runner command line tool.
author: Salomon BRYS <salomon.brys@gmail.com>
homepage: https://github.com/SalomonBrys/Dart-dake
dependencies:
  args: ">=0.11.0+1 <0.12.0"
